version: "3"
services:
  selenium:
    image: selenium/hub
    ports:
      - "4444:4444"
  firefoxnode:
      image: selenium/node-firefox
      environment:
        - HUB_PORT_4444_TCP_ADDR=selenium
        - HUB_PORT_4444_TCP_PORT=4444
      ports:
        - "5555"
      depends_on:
        - selenium
  cucumber-phantomjs:
      build: .
      command: bundle exec cucumber -p poltergeist -f pretty
      volumes:
        - .:/myapp
      ports:
        - "4777:4777"
    